export enum Constant {
    lOGGED_IN = 'You are successfully logged in!',
    lOGGED_OUT = 'You are successfully logged out!',
    RESET_LOGIN = 'Check your email and click the link to reset your password!',
    DEAL_SUCCESS = 'Deal saved successfully!!!',
    DEAL_REMOVE = 'Deal removed permanently!!',
    SIDE_ORDER = 'Side Order saved successfully',
    REMOVE= 'removed permanently!!',
    LINK_COPY = 'Link copied!!!',
    PIZZA_REMOVE = 'Pizza removed permanently!!',
    MEAL_REMOVED = 'Meal removed from database!',
    MEAL_SUCCESS = 'Meal saved succefully!',
    HOTDEAL_DELETION_MSG = 'Hot Deal',
    COMBODEAL_DELETION_MSG = 'Combo Deal',
    SIDEORDER_DELETION_MSG = 'Side Order',
    HOTDEAL_NODE = '/deals/',
    COMBODEAL_NODE = '/comboDeals/',
    SIDEORDER_NODE = '/sideorders/',
    DEAL_NODE = 'deals',
    COMBO_DEAL_NODE = 'comboDeals',
    SIDE_ORDER_NODE = 'sideorders',
    _GALLERY_NODE = 'gallery',
    GALLERY_NODE = '/gallery/',
    GALLERY_IMAGES = 'galleryImages/',
    CONTENT_TYPE = 'image/jpeg/png',
    _PIZZA_NODE = 'pizzas',
    PIZZA_NODE = '/pizzas/',
    SUCCESS_MSG = 'success',
    ERROR_MSG = 'danger'

}
